config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  namespace :users do
    end
  root to: 'visitors#index'
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  resources :users
  # patch 'update_password', on: :collection
  devise_scope :user do
    get 'users/edit/password' => 'users/registrations#edit_password'
    put 'users/edit/update_password/' => 'users/registrations#update_password'
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  validates_presence_of :firstname, :lastname
  validates_uniqueness_of :firstname, :lastname
  has_one :profile, dependent: :destroy
end

app/models/users.rb
module Users
  def self.table_name_prefix
    'users_'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    if current_user.profile.present?
      profile_path(current_user.profile)
    else
      new_profile_path
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def new
    @profile = Profile.new
  end

  def index
    @profiles = Profile.all
  end

  def show
    @profile = current_user.profile
  end

  def edit
    @profile = current_user.profile
  end

  def update
    @profile = current_user.profile
    @profile.update(profile_params)
    redirect_to @profile
  end

  def destroy
    current_user.profile.delete
    redirect_to new_profile_path
  end

  def create
    @profile = current_user.build_profile(profile_params)
    if @profile.save
      redirect_to @profile
    else
      redirect_to new_profile_path
    end
  end

  private

  def profile_params
    params.require(:profile).permit(:age, :school_address)
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]
  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:email, :password, :password_confirmation, :firstname, :lastname, :phonenumber)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:email, :password, :password_confirmation, :firstname, :lastname, :phonenumber, :current_password)}
  end

  def edit_password
    @user = current_user
  end

  def update_password
    @user = User.find(current_user.id)
    if @user.update_with_password(user_params)
      sign_in @user, :bypass => true
      redirect_to root_url
      flash[:notice] = "Your account has been updated successfully."
    else
      render "users/registrations/edit_password"
    end
  end

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  private

  def user_params
    params.required(:user).permit(:password, :password_confirmation, :current_password)
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
  
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users/profiles_helper.rb
module Users::ProfilesHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <%= link_to 'Home', root_path, class: 'navbar-brand' %>
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <% if current_user.profile.present? %>
    <li><%= link_to 'Edit Profile', edit_profile_path(current_user.profile) %></li>
  <% else %>
    <li><%= link_to 'Create Profile', new_profile_path %></li>
  <% end %>

  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "My Portfolio" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "My Portfolio" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "intlTelInput" %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" type="text/css" href="/assets/intlTelInput.css">
    <script type="text/javascript" src="assets/intlTelInput.js"></script>
    <script type="text/javascript" src="assets/util.js"></script>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <div style="margin-top:50px;">
        <%= content_for?(:error_header) ? '' : (render 'layouts/messages') %>
      </div>       
       <%= yield %>
    </main>
  </body>
</html>

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :age %><br>
    <%= f.number_field :age, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :school_address %><br>
    <%= f.text_field :school_address, placeholder: "School Address", class: 'form-control' %>
  </div>
  <%= f.submit 'Submit', :class => 'btn btn-primary' %>
<% end %>

app/views/profiles/edit.html.erb
<div class="container">
  <div class="row">
    <div class="profile-wrapper">

      <h1>Editing Profile</h1>

      <%= render 'form' %>

      <%= link_to 'Show', @profile %> |
      <%= link_to 'Back', profiles_path %> |
      <%= link_to 'Destroy', @profile, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  </div>
</div>

app/views/profiles/index.html.erb
<div class="container">
  <div class="row">
    <div class="profile-wrapper">

      <p id="notice"><%= notice %></p>

      <h1>Listing Profiles</h1>

      <table>
        <thead>
          <tr>
            <th>Age</th>
            <th>School address</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @profiles.each do |profile| %>
            <tr>
              <td><%= profile.age %></td>
              <td><%= profile.school_address %></td>
              <td><%= link_to 'Show', profile %></td>
              <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
              <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Profile', new_profile_path %>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="container">
  <div class="row">
    <div class="profile-wrapper">
      <h1>New Profile</h1>

      <%= render 'form' %>

      <%= link_to 'Back', profiles_path %>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="container">
  <div class="row">
    <div class="profile-wrapper">
      <p id="notice"><%= notice %></p>

      <p>
        <strong>Age:</strong>
        <%= @profile.age %>
      </p>

      <p>
        <strong>School address:</strong>
        <%= @profile.school_address %>
      </p>

      <%= link_to 'Edit', edit_profile_path(@profile) %> |
      <%= link_to 'Back', profiles_path %> |
      <%= link_to 'Destroy', @profile, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  </div>
</div>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<div class="authform">
  <div class="form-group">
    <h1>Welcome</h1>
  </div>
</div>